// Player
export const SET_PLAYER_NAME = 'SET_PLAYER_NAME';
export const SET_DIFFICULTY = 'SET_DIFFICULTY';
export const SET_SESSION_TOKEN = 'SET_SESSION_TOKEN';
export const SET_PLAYER_CATEGORY = 'SET_PLAYER_CATEGORY';