export const START_NEW_GAME = "START_NEW_GAME";

// Player
export const SET_PLAYER_NAME = "SET_PLAYER_NAME";
export const SET_DIFFICULTY = "SET_DIFFICULTY";
export const SET_SESSION_TOKEN = "SET_SESSION_TOKEN";
export const SET_PLAYER_CATEGORY = "SET_PLAYER_CATEGORY";

// Questions
export const SET_NUMBER_OF_QUESTIONS = "SET_NUMBER_OF_QUESTIONS";
export const SET_NUMBER_OF_CORRECT_ANSWERS = "SET_NUMBER_OF_CORRECT_ANSWERS";
export const SET_NUMBER_OF_WRONG_ANSWERS = "SET_NUMBER_OF_WRONG_ANSWERS";
export const SET_NUMBER_OF_SKIPPED_QUESTIONS =
  "SET_NUMBER_OF_SKIPPED_QUESTIONS";
export const SET_NUMBER_OF_CATEGORIES = "SET_NUMBER_OF_CATEGORIES";
export const SET_TOTAL_TIME_SPENT = "SET_TOTAL_TIME_SPENT";
export const SET_RESET_STATE = "SET_RESET_STATE";
